---
title: "DeNoPa and RBD, olfaction and fluid biomarkers"
author: "Juan Li"
date: "2023-11-13"
output:  
  bookdown::html_document2:
    toc: true
    number_sections: true
    toc_float: true
    fig_caption: yes
    global_numbering: true 
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=8
)
```

# Load packages

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(lubridate)
library(pROC)
library(ggplot2)
library(ggpmisc)
library(ggtext)
library(ggpubr)
library(rms)
library(pracma)
library(dabestr) # https://acclab.github.io/dabestr/
library(ggbeeswarm)
library(rlang)
library(tidyr)
```

# Read in and prepare the data

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_BL <- read.csv("Baseline_cut.csv", header = TRUE)
```

```{r}
df_BL$group <- factor(df_BL$group, levels = c("HC", "PD", "OND", "RBD_Not converted", "RBD_Converted"))

df_BL <- df_BL %>% mutate(diagnosis = ifelse(!is.na(diagnosis), diagnosis, as.character(group)))
vec <- unique(df_BL$diagnosis)[!(unique(df_BL$diagnosis) %in% c("HC", "PD", "RBD_Not converted"))]
df_BL$diagnosis <- factor(df_BL$diagnosis, levels = c("HC", "PD", vec[order(vec)], "RBD_Not converted"))
```

# Score distribution of SST.ID, the estimation plots

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=13}
multi.group <- 
  df_BL %>%
  arrange(diagnosis) %>% 
  dabest(group, SST.ID, 
         idx = list(c("HC", "PD", "OND","RBD_Not converted", "RBD_Converted")),
         paired = FALSE
        )

multi.group.mean_diff <- multi.group %>% mean_diff() 

# plot
group.names <- levels(df_BL$diagnosis)
my.colors <- c("#A6CEE3", "#E31A1C", "darkred", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#FDBF6F", "#FF7F00", "#6A3D9A")
custom.pal <- setNames(my.colors, group.names)

plot(multi.group.mean_diff, color.column = diagnosis, palette = custom.pal,
     swarmplot.params=list(shape=15),
     rawplot.ylabel = paste("SST ID score", "at baseline", sep = "\n"),
     effsize.ylabel = paste("Unpaired mean", "difference in score", sep = "\n"))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
pairwise.t.test(df_BL$SST.ID, df_BL$group, p.adjust.method="bonferroni")
```

## Fig 1a

```{r}
# Classify olfaction based on the updated norm of SST
# At each age and sex category:
# Reduced: <= 10%

df_BL <- df_BL %>% 
  mutate(olfaction = case_when(
    # Female, <= 30
    sex == "Female" & age <= 30 & SST.ID <= 11   ~ "Reduced",
    sex == "Female" & age <= 30                  ~ "Normal",
    # Male, <= 30
    sex == "Male"   & age <= 30 & SST.ID <= 11 ~ "Reduced",
    sex == "Male"   & age <= 30                ~ "Normal",
    # Female, <= 40
    sex == "Female" & age <= 40 & SST.ID <= 12 ~ "Reduced",
    sex == "Female" & age <= 40                ~ "Normal",
    # Male, <= 40
    sex == "Male"   & age <= 40 & SST.ID <= 12 ~ "Reduced",
    sex == "Male"   & age <= 40                ~ "Normal",
    # Female, <= 50
    sex == "Female" & age <= 50 & SST.ID <= 11 ~ "Reduced",
    sex == "Female" & age <= 50                ~ "Normal",
    # Male, <= 50
    sex == "Male"   & age <= 50 & SST.ID <= 11 ~ "Reduced",
    sex == "Male"   & age <= 50                ~ "Normal",
    # Female, <= 60
    sex == "Female" & age <= 60 & SST.ID <= 11 ~ "Reduced",
    sex == "Female" & age <= 60                ~ "Normal",
    # Male, <= 60
    sex == "Male"   & age <= 60 & SST.ID <= 10 ~ "Reduced",
    sex == "Male"   & age <= 60                ~ "Normal",
    # Female, <= 70
    sex == "Female" & age <= 70 & SST.ID <= 10  ~ "Reduced",
    sex == "Female" & age <= 70                 ~ "Normal",
    # Male, <= 70
    sex == "Male"   & age <= 70 & SST.ID <= 9 ~ "Reduced",
    sex == "Male"   & age <= 70               ~ "Normal",
    # Female, <= 80
    sex == "Female" & age <= 80 & SST.ID <= 7 ~ "Reduced",
    sex == "Female" & age <= 80               ~ "Normal",
    # Male, <= 80
    sex == "Male"   & age <= 80 & SST.ID <= 7 ~ "Reduced",
    sex == "Male"   & age <= 80               ~ "Normal",
    # Female, over 80
    sex == "Female" & SST.ID <= 3.8 ~ "Reduced",
    sex == "Female"                 ~ "Normal",
    # Male, over 80
    sex == "Male"   & SST.ID <= 5    ~ "Reduced",
    sex == "Male"                    ~ "Normal"
  ))

df_BL$olfaction[is.na(df_BL$SST.ID)] <- NA

df_BL$olfaction <- factor(df_BL$olfaction, levels = c("Normal", "Reduced"))
```

Remove one RBD participant who is younger than 40yrs

```{r, fig.height=4, fig.width=10}
ggplot(df_BL %>% filter(age>=40), aes(age, SST.ID, color = olfaction)) +
  geom_point(alpha = 0.8, shape = 15)+
  scale_color_manual(values = c("blue", "darkorange"))+
  facet_grid(rows = vars(sex), cols = vars(group)) +
  labs(x = "Age at Baseline (yrs)",
       y = "SST-ID Score at Baseline")+
  theme_bw()+
  theme(text = element_text(size=14),
        legend.position = "bottom")
```

# olfaction vs CSF SAA, Fig 1c 

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=13}
df_BL$CSF_SAA <- factor(df_BL$CSF_SAA, levels = c("Positive", "Negative"))
multi.group <- 
  df_BL %>% filter(!is.na(SST.ID), !is.na(CSF_SAA)) %>% 
  arrange(CSF_SAA) %>% 
  dabest(group, SST.ID, 
         idx = list(c("HC", "PD", "OND", 
                      "RBD_Not converted", "RBD_Converted")),
         paired = FALSE
        )

multi.group.mean_diff <- multi.group %>% mean_diff() 

# plot
plot(multi.group.mean_diff, color.column = CSF_SAA,
     swarmplot.params=list(shape=1),
     rawplot.ylabel = paste("SST ID score", "at baseline", sep = "\n"),
     effsize.ylabel = paste("Unpaired mean", "difference in score", sep = "\n"))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=13}
fit <- glm(CSF_SAA ~ age + sex + group, data = df_BL, family = "binomial")
summary(fit)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=5, fig.width=13}
fit <- lm(as.numeric(CSF_SAA) ~ SST.ID, data = df_BL)
summary(fit)
```

```{r}
# Point Biserial Correlation
cor.test(df_BL$SST.ID, as.numeric(df_BL$CSF_SAA))
```

```{r}
roc_1 <- roc(df_BL$group, df_BL$SST.ID, levels=c("HC","PD"),na.rm=TRUE, ci=TRUE) 
paste("SST ID to classify PD versus HC: AUC = ", round(roc_1$auc,2), " (95% CI ",round(roc_1$ci[1],2),"-",round(roc_1$ci[3],2),")", sep = "")

roc_2 <- roc(df_BL$group, as.numeric(df_BL$CSF_SAA), levels=c("HC","PD"),na.rm=TRUE,ci=TRUE)
paste("CSF SAA to classify PD versus HC: AUC = ", round(roc_2$auc,2), " (95% CI ",round(roc_2$ci[1],2),"-",round(roc_2$ci[3],2),")", sep = "")

roc_3 <- roc(df_BL$CSF_SAA, df_BL$SST.ID, levels=c("Negative", "Positive"),na.rm=TRUE,ci=TRUE)
paste("SST ID to classify CSF SAA status: AUC = ", round(roc_3$auc,2), " (95% CI ",round(roc_3$ci[1],2),"-",round(roc_3$ci[3],2),")", sep = "")

cbind(roc_3$thresholds, round(roc_3$sensitivities,2), round(roc_3$specificities,2), round(roc_3$sensitivities + roc_3$specificities,2))

ci.coords(roc_3, x=10, input = "threshold", 
          ret=c("sensitivity", "specificity"))
```

## Supplementary Figure S2 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
biomarkers <- c("alpha_synuclein", "t_tau", "p_tau", "ab42", "total_protein",  
                "alpha_synuclein_norm", "t_tau_norm", "p_tau_norm", "ab42_norm")
title_str <- c("\u03b1-Synuclein (pg/mL)",	
               "T-tau (pg/mL)",
               "P-tau (pg/mL)",
               "A\u03b242 (pg/mL)",
               "Total Protein (mg/L)",
               "Normalized \u03b1Synuclein (pg/\u03bcg)",	
               "Normalized T-tau (pg/\u03bcg)",
               "Normalized P-tau (pg/\u03bcg)",
               "Normalized A\u03b242 (pg/\u03bcg)")

for (biomarker in biomarkers) {
  dfPlt <- df_BL %>% 
    select(group, SST.ID, CSF_SAA, all_of(biomarker), sex, age, olfaction)
  names(dfPlt)[4] <- "biomarker"
  
  roc_1 <- roc(dfPlt$group, dfPlt$biomarker, levels=c("HC", "PD"),na.rm=TRUE, ci=TRUE) 
  
  print(biomarker)
  
  # AUC of HC vs PD
  print(paste0("AUC value of HC vs PD: ", round(roc_1$auc,2), " (95% CI ", 
         round(roc_1$ci[1],2), "-", round(roc_1$ci[3],2), ")"))
  
  # correlation with CSF SAA
  print(cor.test(dfPlt$biomarker,as.numeric(dfPlt$CSF_SAA)))
  
  # lr
  fit <- lm(biomarker ~ group + age + sex + olfaction, data = dfPlt)
  print(summary(fit))
}
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.height=6.5, fig.width=9}
for (i in seq_len(length(biomarkers))) {
  biomarker <- biomarkers[i]
  dfPlt <- df_BL %>% select(group, olfaction, all_of(biomarker), sex)
  names(dfPlt)[3] <- "biomarker"
  
  dfPlt$group_sex <- paste(dfPlt$sex, dfPlt$group, sep = "_")
  multi.group <- 
    dfPlt %>% filter(!is.na(biomarker), !is.na(olfaction)) %>% 
    dabest(group_sex, biomarker, 
           idx = list(c("Male_HC", "Male_PD", "Male_OND"),
                      c("Female_HC", "Female_PD", "Female_OND")),
           paired = FALSE
    )
  
  multi.group.mean_diff <- multi.group %>% mean_diff() 
  
  olfaction.names <- levels(dfPlt$olfaction)
  my.colors <- c("blue", "darkorange", "black")
  custom.pal <- setNames(my.colors, olfaction.names)

  # plot
  print(plot(multi.group.mean_diff, color.column = olfaction, palette = custom.pal,
       swarmplot.params=list(alpha = 0.5),
       rawplot.ylabel = paste(title_str[i], "at baseline", sep = "\n"),
       effsize.ylabel = paste("Unpaired mean", "difference in score", sep = "\n")))
}
```

## Fig 1b - All

```{r}
df_time <- read.csv("Time_cut.csv", header = TRUE)
df_time <- df_time %>% filter(group != "OND")
df_time$group <- factor(df_time$group, levels = c("HC", "PD", "RBD_Not converted", "RBD_Converted"))
```

```{r, fig.height=8, fig.width=6}
df_F <- df_time %>% filter(sex == "Female")
levels(df_F$group) <- c(paste0("HC (n = ", nrow(df_F %>% filter(month == 0, group == "HC")), ")"),
                        paste0("PD (n = ", nrow(df_F %>% filter(month == 0, group == "PD")), ")"),
                        paste0("RBD_Not converted (n = ", nrow(df_F %>% filter(month == 0, group == "RBD_Not converted")), ")"),
                        paste0("RBD_Converted (n = ", nrow(df_F %>% filter(month == 0, group == "RBD_Converted")), ")"))
p_F <- ggplot(df_F, aes(month, SST.ID, group = ID, color = group)) +
  geom_point(alpha = 0.1, shape = 15)+
  geom_line(alpha = 0.1)+
  geom_smooth(aes(group = group), method = "lm", se = FALSE, linewidth=2)+
  scale_x_continuous(breaks = c(0,24,48,72,96, 120))+
  scale_y_continuous(breaks = seq(from = 0, to = 16, by = 2))+
  scale_color_manual(values = c("#A6CEE3", "#E31A1C", "#6A3D9A", "darkred"))+
  theme_bw()+
  theme(text = element_text(size = 14),
        legend.title = element_blank())+
  labs(title = "Female",
       x = "Months since baseline",
       y = "SST-ID Score")

df_M <- df_time %>% filter(sex == "Male")
levels(df_M$group) <- c(paste0("HC (n = ", nrow(df_M %>% filter(month == 0, group == "HC")), ")"),
                        paste0("PD (n = ", nrow(df_M %>% filter(month == 0, group == "PD")), ")"),
                        paste0("RBD_Not converted (n = ", nrow(df_M %>% filter(month == 0, group == "RBD_Not converted")), ")"),
                        paste0("RBD_Converted (n = ", nrow(df_M %>% filter(month == 0, group == "RBD_Converted")), ")"))
p_M <- ggplot(df_M, aes(month, SST.ID, group = ID, color = group)) +
  geom_point(alpha = 0.1, shape = 15)+
  geom_line(alpha = 0.1)+
  geom_smooth(aes(group = group), method = "lm", se = FALSE, linewidth=2)+
  scale_x_continuous(breaks = c(0,24,48,72,96, 120))+
  scale_y_continuous(breaks = seq(from = 0, to = 16, by = 2))+
  scale_color_manual(values = c("#A6CEE3", "#E31A1C", "#6A3D9A", "darkred"))+
  theme_bw()+
  theme(text = element_text(size = 14),
        legend.title = element_blank())+
  labs(title = "Male",
       x = "Months since baseline",
       y = "SST-ID Score")

ggarrange(p_F, p_M, nrow = 2)
```

## Supplementary Figure S1

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_rate <- df_time %>% 
  arrange(month) %>% 
  group_by(ID) %>% 
  mutate(diff = SST.ID - lag(SST.ID),
         time_diff = month - lag(month)) %>% 
  rowwise() %>% 
  mutate(rate = diff/time_diff) %>% 
  mutate(rate = ifelse(month==0, 0, rate))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(df_rate, aes(month, rate, group = ID, color = group)) +
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_point(alpha = 0.1)+
  geom_line(alpha = 0.1)+
  geom_smooth(aes(group = group), method = "lm", se = FALSE, size=2)+
  scale_x_continuous(breaks = c(0,24,48,72,96, 120))+
  scale_color_manual(values = c("#A6CEE3", "#E31A1C", "#6A3D9A", "darkred"))+
  facet_wrap(~sex)+
  theme_bw()+
  theme(text = element_text(size = 12),
        legend.position = "bottom")+
  labs(x = "Months since baseline",
       y = "Rate of score changes (point/month)")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_rate <- df_rate %>% left_join(df_BL %>% select(ID, age), by = "ID")
df_rate <- df_rate %>% mutate(age = age + month/12)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
fit1 <- lm(rate ~ month + group + age + sex, data = df_rate)
summary(fit1)
```

```{r}

```

